# Generated by Django 5.1.3 on 2024-11-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polera',
            old_name='decripcion',
            new_name='descripcion',
        ),
    ]
